[package]
name = "rotom_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slack-hook2 = "0.10.1"
tokio = { version = "1.25.0", features = ["full"] }
